//go:build ignore

package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
)

var dict = map[string]string{
	"API唤醒通道":             "ApiWakeChan",
	"api辅助协程生命周期":         "ApiGuardCtx",
	"http报错":              "HttpErr",
	"http接口":              "HttpBind",
	"事件通道":                "EventBus",
	"信号通道":                "SignalPipe",
	"html头":               "HtmlHead",
	"json头":               "JsonHead",
	"keepAlive头":          "KeepAliveHead",
	"noCache头":            "NoCacheHead",
	"plain头":              "PlainHead",
	"sse头":                "SseHead",
	"sse观察者矩阵":            "SseObserverMatrix",
	"代理客户端":               "ProxyClient",
	"SteamCMD下载缓冲池":       "SteamCmdDlPool",
	"SteamCMD解压缓冲池_Linux": "SteamCmdUnzipPool_Linux",
	"SteamCmd可执行文件":       "SteamCmdExe",
	"SteamCmd程序":          "SteamCmdBin",
	"SteamCmd路径":          "SteamCmdPath",
	"steamcmd下载链接":        "SteamCmdUrl",
	"steamcmd文件名":         "SteamCmdName",
	"steamcmd进程":          "SteamCmdProc",
	"steamcmd默认路径":        "SteamCmdDefPath",
	"acf文件目录":             "AcfDir",
	"home目录":              "HomeDir",
	"ps脚本":                "PsScript",
	"zip读取器":              "ZipReader",
	"作业信息类_扩展限制":          "JobObjectExtLimit",
	"作业组句柄":               "JobGroupHandle",
	"id锚点":                "IdAnchor",
	"key起始":               "KeyStart",
	"val起始":               "ValStart",
	"偏移量":                 "Offset",
	"位置":                  "Pos",
	"值":                   "Val",
	"信息":                  "Info",
	"临时":                  "Temp",
	"临时文件":                "TempFile",
	"临时游标":                "TmpCursor",
	"临时缓冲":                "TmpBuffer",
	"临时路径":                "TmpPath",
	"万分比CPU":              "CpuBps",
	"上次K":                 "LastKTime",
	"上次U":                 "LastUTime",
	"上次周期":                "LastCycle",
	"上次时间点":               "LastTimestamp",
	"上次滴答":                "LastTicks",
	"上次监控快照":              "LastSysSnapshot",
	"上次系统时间":              "LastSysTime",
	"下一次播报":               "NextAnnounce",
	"下载数据":                "DlData",
	"世代":                  "Epoch",
	"世界天数":                "WorldDays",
	"保存完成信号":              "SaveAckSig",
	"允许控制台输出":             "AllowConsoleOut",
	"允许服务器运行原子锁":          "ServerRunGate",
	"优雅重启等待时间":            "GraceWaitTime",
	"克劳斯":                 "Klaus",
	"克劳斯倒计时":              "KlausTimer",
	"主世界OK":               "MasterOk",
	"主世界world配置文件路径":      "MasterWorldConfPath",
	"主世界世代同步链路":           "MasterEpochLink",
	"主世界世代观察者":            "MasterEpochWatcher",
	"主世界命令通道":             "MasterCmdPipe",
	"主世界寄生虫心跳":            "MasterParasitePulse",
	"主世界就绪原子锁":            "MasterReadyGate",
	"主世界当前世代":             "MasterEpoch",
	"主世界探针轮询器":            "MasterRadar",
	"主世界接收器存活":            "MasterRxAlive",
	"主世界日志路径":             "MasterLogPath",
	"主世界是否开启":             "IsMasterEnabled",
	"主世界输入":               "MasterStdin",
	"主世界输出":               "MasterStdout",
	"主世界进程":               "MasterProc",
	"主世界错误":               "MasterStderr",
	"setup独有":             "SetupExclusive",
	"setup独有字典":           "SetupOnlyDict",
	"全局API缓冲":             "GlobalApiBuffer",
	"全局世代心跳":              "GlobalEpochPulse",
	"全局向量缓存":              "GlobalVecCache",
	"全局报文指针":              "GlobalPacketPtr",
	"全局本地模组时间表":           "LocalModEpochs",
	"全局本地模组缓存锁":           "LocalModCacheLock",
	"全局模组API缓冲锁":          "ModApiBufferLock",
	"全局目标模组缓存":            "GlobalTargetModCache",
	"全局行缓存":               "GlobalLineCache",
	"全局远程模组时间表":           "RemoteModEpochs",
	"全局远程模组缓存锁":           "RemoteModCacheLock",
	"全局局部生命周期终结":          "EpochKillSwitch",
	"全局生命周期":              "GlobalCtx",
	"全局生命周期终结":            "GlobalKillSwitch",
	"全局配置":                "GlobalConf",
	"全服监控态":               "ClusterMonState",
	"全服资源探针任务":            "ClusterProbeTask",
	"公告_优雅重启上半":           "AnnounceGraceRebootPrefix",
	"公告_优雅重启下半":           "AnnounceGraceRebootSuffix",
	"动作总线":                "ActionBus",
	"动作_无动作":              "Action_Noop",
	"动作_主世界崩溃":            "Action_MasterCrash",
	"动作_洞穴崩溃":             "Action_CavesCrash",
	"动作_执行系统关机":           "Action_SystemHalt",
	"动作_执行API强制关闭":        "Action_ApiHalt",
	"动作_执行游戏本体更新":         "Action_GameUpdate",
	"动作_执行模组热更新":          "Action_ModHotUpdate",
	"合体PID":               "PackedPID",
	"复合状态字节":              "PackedStateByte",
	"复合环境字节":              "PackedEnvByte",
	"字符合法表":               "CharacterValidityTable",
	"去除位掩码":               "StripBitmask",
	"字节Mem":               "ByteMem",
	"内存计":                 "MemGauge",
	"内存读取器":               "MemReader",
	"单槽位容量":               "SlotCap",
	"处理游标":                "ScanCursor",
	"分支锚点":                "BranchAnchor",
	"前缀部分":                "PrefixChunk",
	"前缀干净":                "CleanPrefix",
	"后缀干净":                "CleanSuffix",
	"可能ID":                "ProbeID",
	"右引号":                 "RightQuote",
	"右引号位置":               "RightQuotePos",
	"包含中文":                "HasNonASCII",
	"压扁":                  "Flatten",
	"句柄":                  "vHandle",
	"原子写文件":               "AtomicWriteFile",
	"原子写文件流":              "AtomicWriteStream",
	"冲刷器":                 "vFlusher",
	"获取文件快照":              "ReadSnapshot",
	"安全读取器":               "GuardedReader",
	"写入的文件":               "vWriteFile",
	"写入字节数":               "WrittenBytes",
	"压缩内容":                "DeflatedData",
	"完整程序路径":              "FullBinPath",
	"复制文件":                "CloneFile",
	"初始空状态":               "ZeroState",
	"初始化核心中枢":             "BootNucleus",
	"初始化游戏内状态":            "InitGameState",
	"启动高性能底层监听":           "BootRawListener",
	"启动本地api接口":           "BootLocalApi",
	"启动后自动安装":             "AutoInstallOnBoot",
	"刷新服务器状态":             "FlushServerState",
	"加载配置":                "LoadConfig",
	"加载器存在":               "HasLoader",
	"加载器路径":               "LoaderPath",
	"命令api原子锁":            "ApiCmdGate",
	"原子锁":                 "AtomicGate",
	"启用寄生":                "EnableParasite",
	"启用CPU膨胀探测":           "EnableCpuInflationProbe",
	"启用主世界":               "EnableMaster",
	"启用洞穴":                "EnableCaves",
	"启用自动更新":              "EnableAutoUpdate",
	"启用崩溃重启":              "EnableCrashReboot",
	"启用负载均衡":              "EnableLoadBalance",
	"发起竞速请求":              "FireRacingRequest",
	"发起请求":                "FireRequest",
	"发送纯文本指令":             "EmitRawCmd",
	"安全投递":                "ForcePushCmd",
	"命令目标":                "CmdTarget",
	"发往全服":                "RouteToAll",
	"发往主世界":               "RouteToMaster",
	"发往洞穴":                "RouteToCaves",
	"协议":                  "Protocol",
	"原始载荷":                "RawPayload",
	"响应":                  "Resp",
	"响应体":                 "RespBody",
	"回显污染头":               "EchoTaintHead",
	"动态寄生虫指令":             "DynamicParasiteCmd",
	"声呐探测指令":              "SonarPingCmd",
	"存档名称":                "ClusterName",
	"存档根目录":               "StorageRoot",
	"在线玩家人数":              "OnlinePlayers",
	"天体唤醒":                "CelestialWake",
	"大鹅":                  "MooseGoose",
	"大鹅倒计时":               "MooseGooseTimer",
	"季节":                  "Season",
	"季节剩余":                "SeasonLeft",
	"季节剩余天数":              "SeasonDaysLeft",
	"天数":                  "Days",
	"公告_游戏更新":             "AnnounceGameUpdate",
	"公告_模组更新":             "AnnounceModUpdate",
	"公告语言":                "AnnounceLang",
	"公告语言初始化":             "InitAnnounceLang",
	"命令":                  "vCmd",
	"内容":                  "RawContent",
	"存在":                  "Exists",
	"失败计数":                "FailCount",
	"参数":                  "vArgs",
	"频率":                  "Frequency",
	"命中":                  "IsHit",
	"头部":                  "vHeader",
	"前缀":                  "Prefix",
	"后缀":                  "Suffix",
	"字段":                  "vField",
	"字段类型":                "FieldType",
	"字符":                  "Char",
	"安装SteamCMD":          "InstallSteamCmd",
	"安装游戏":                "InstallGame",
	"巨鹿":                  "Deerclops",
	"巨鹿倒计时":               "DeerclopsTimer",
	"差异模组":                "DeltaMods",
	"新CavesTicks":         "NewCavesTicks",
	"当前季节":                "CurrSeason",
	"当前对方世代":              "CurrPeerEpoch",
	"当前主世界世代":             "CurrMasterEpoch",
	"当前频率":                "CurrFrequency",
	"当前状态快照":              "CurrStateSnap",
	"当前总滴答":               "CurrTotalTicks",
	"当前滴答":                "CurrTick",
	"当前Ticks":             "CurrTicks",
	"局部最大震荡周期":            "MaxJitterCycle",
	"CPU频率":               "CPUFrequency",
	"尾部游标":                "TailCursor",
	"数据起始游标":              "DataStartCursor",
	"左引号位置":               "LeftQuotePos",
	"括号结束":                "BracketEnd",
	"找到等号":                "EqFound",
	"当前ID":                "CurrID",
	"当前ID被禁用":             "IsIDDisabled",
	"当前字节":                "CurrByte",
	"当前索引":                "CurrIdx",
	"引号":                  "Quote",
	"数字串":                 "NumStr",
	"数字开始":                "NumStart",
	"数字结束":                "NumEnd",
	"数字起点":                "NumOrigin",
	"排重字典":                "DedupSet",
	"底层监听器":               "RawListener",
	"底层管道":                "RawPipe",
	"扁平网关":                "FlatGateway",
	"接收缓冲池":               "RxPool",
	"客户端推送通道":             "ClientTxPipe",
	"实际写入数量":              "ActualWritten",
	"拷贝字节数":               "CopiedBytes",
	"总长":                  "TotalLen",
	"总长度":                 "TotalLength",
	"总长文件":                "TotalLenFile",
	"总长模板":                "TotalLenTpl",
	"已解压总量":               "UnzippedTotal",
	"归档读取器":               "ArchiveReader",
	"扫描器":                 "Scanner",
	"数据":                  "vData",
	"数量缓存":                "CountCache",
	"客户端拔管":               "ForceDropClient",
	"掐断请求":                "AbortReq",
	"探针取消":                "CancelProbe",
	"捕获的信号":               "CaughtSig",
	"崩溃动作":                "CrashAction",
	"执行优雅重启":              "GracefulReboot",
	"执行模组更新":              "ExecModUpdate",
	"执行游戏更新":              "ExecGameUpdate",
	"拼接进程路径":              "JoinProcPath",
	"探测模组更新":              "ProbeModUpdate",
	"探测游戏更新":              "ProbeGameUpdate",
	"提取stat字段":            "ExtractStat",
	"对象":                  "Entity",
	"平台专属属性":              "PlatformAttrs",
	"扩展限制结构体":             "ExtLimitStruct",
	"指针":                  "vPtr",
	"寻址掩码":                "AddrMask",
	"延长码FF":               "ExtCodeFF",
	"指令":                  "Instr",
	"指令流":                 "InstrStream",
	"指令字符串":               "CmdStr",
	"寄生指令":                "ParasiteCmd",
	"报文指针":                "PacketPtr",
	"探针":                  "Probe",
	"探针私有快照":              "ProbeSnap",
	"探针缓冲池":               "ProbePool",
	"控制台换行符":              "ConsoleNL",
	"控制台合并输出":             "LogOut",
	"控制台合并输出换行":           "LogOutLn",
	"实时输出流":               "LiveStream",
	"提示消息":                "PromptMsg",
	"展示地址":                "ViewAddr",
	"接口地址":                "BindAddr",
	"控制器":                 "Controller",
	"文件":                  "vFile",
	"文件集":                 "FileSet",
	"文件索引":                "FileIdx",
	"文件读写原子锁":             "FileIOGate",
	"文件路径":                "FilePath",
	"当前文件":                "CurrFile",
	"当前盘面内容":              "CurrDiskContent",
	"实际路径":                "RealPath",
	"强转成功":                "CastOk",
	"投递成功":                "DeliverOk",
	"就绪标记":                "ReadyFlag",
	"定时器":                 "Timer",
	"客户端":                 "vClient",
	"当前槽位":                "CurrSlot",
	"当前间隔":                "CurrInterval",
	"实际向量数":               "ActualVecs",
	"实际长度":                "ActualLen",
	"按行分割":                "SplitByLine",
	"暴动状态":                "NightmareState",
	"暴动阶段":                "NightmarePhase",
	"熊大":                  "Bearger",
	"熊大倒计时":               "BeargerTimer",
	"果蝇王":                 "FruitFlyLord",
	"果蝇王倒计时":              "FruitFlyLordTimer",
	"昼夜阶段":                "DayPhase",
	"月相":                  "MoonPhase",
	"月相状态":                "MoonState",
	"是否下雨":                "IsRaining",
	"是否下雪":                "IsSnowing",
	"游戏内状态":               "GameState",
	"新K":                  "NewKTime",
	"新U":                  "NewUTime",
	"新MasterTicks":        "NewMasterTicks",
	"时间差":                 "TimeDelta",
	"时间差纳秒":               "DeltaNanos",
	"滴答差":                 "TickDelta",
	"时间数字":                "TimeStr",
	"时间锚点":                "TimeAnchor",
	"核心CPU指标":             "CoreCpuMetrics",
	"检查更新间隔":              "UpdateCheckInterval",
	"检查间隔":                "CheckInterval",
	"栈缓冲":                 "StackBuf",
	"新缓冲":                 "vNewBuffer",
	"新游标":                 "NewCursor",
	"检测游标":                "ProbeCursor",
	"新容量":                 "NewCap",
	"池化指针":                "PooledPtr",
	"物理上限":                "HardLimit",
	"物理引擎":                "PhysicsEngine",
	"深度":                  "Depth",
	"温度高位":                "TempHi",
	"测试矩阵":                "TestMatrix",
	"死亡传感器":               "DoomSensor",
	"模组正在更新":              "ModUpdatingGate",
	"游戏正在更新":              "GameUpdatingGate",
	"正在手动关闭原子锁":           "ManualHaltGate",
	"正在重启原子锁":             "RebootingGate",
	"洞穴就绪原子锁":             "CavesReadyGate",
	"洞穴OK":                "CavesOk",
	"洞穴world配置文件路径":       "CavesWorldConfPath",
	"洞穴世代同步链路":            "CavesEpochLink",
	"洞穴世代观察者":             "CavesEpochWatcher",
	"洞穴命令通道":              "CavesCmdPipe",
	"洞穴寄生虫心跳":             "CavesParasitePulse",
	"洞穴当前世代":              "CurrCavesEpoch",
	"洞穴探针轮询器":             "CavesRadar",
	"洞穴接收器存活":             "CavesRxAlive",
	"洞穴日志路径":              "CavesLogPath",
	"洞穴状态上报端点":            "CavesStateEndpoint",
	"洞穴输入":                "CavesStdin",
	"洞穴输出":                "CavesStdout",
	"洞穴进程":                "CavesProc",
	"洞穴错误":                "CavesStderr",
	"检查linux运行环境":         "CheckLinuxEnv",
	"游戏主程序路径":             "GameBinPath",
	"游戏程序目录":              "GameBinDir",
	"模组Lua更新文件目标路径":       "ModLuaTarget",
	"模组Lua更新备份":           "ModLuaBackup",
	"模组配置文件路径":            "ModConfPath",
	"源流":                  "SrcStream",
	"源码":                  "SrcCode",
	"源路径":                 "SrcPath",
	"源文件":                 "SrcFile",
	"校验配置是否为原始默认版本":  "IsFactoryDefault",
	"是否写入默认配置":       "WriteDefaultConf",
	"是否为变量字符":        "IsVarChar",
	"是标识符":           "IsIdent",
	"是纯数字":           "IsNumeric",
	"标签":             "vTag",
	"标识符":            "Ident",
	"有效ID":           "ValidID",
	"有效数字":           "ValidNum",
	"有效数据":           "ValidData",
	"模组ID":           "ModID",
	"模组列表":           "ModList",
	"最终指令":           "FinalCmd",
	"最终更新名单":         "FinalUpdateList",
	"最终长度":           "FinalLen",
	"极速二进制协议头":       "RawProtoMagic",
	"极速网关":           "SonicGateway",
	"模拟主体":           "MockBody",
	"模拟方法":           "MockMethod",
	"模拟路由":           "MockRoute",
	"日志状态":           "LogState",
	"日志读取池":          "LogReaderPool",
	"标准输出句柄":         "StdoutHandle",
	"本地时间":           "LocalTime",
	"本地时间表":          "LocalEpochMap",
	"本地版本":           "LocalVer",
	"版本号":            "VerNum",
	"最大重试次数":         "MaxRetries",
	"清洗命令通道":         "FlushCmdPipe",
	"核心数":            "NumCores",
	"核心执行动作":         "KernelAction",
	"特征ID":           "SigID",
	"特征_保存完成":        "Sig_Saved",
	"特征_模拟暂停":        "Sig_SimPaused",
	"特征_模组过期":        "Sig_ModOutdated",
	"特征_玩家聊天前缀":      "Sig_PlayerChat",
	"特征时间":           "SigTime",
	"特征时间前缀":         "SigTimePrefix",
	"状态_执行失败":        "State_Fail",
	"状态_执行成功":        "State_OK",
	"状态_无资源更新":       "State_NoUpdate",
	"状态_锁拦截":         "State_Locked",
	"状态环形阵列":         "StateRingBuf",
	"状态码":            "vStatusCode",
	"状态锁":            "StateLock",
	"环形游标":           "RingCursor",
	"环形缓冲深度":         "RingBufDepth",
	"第31位错误标记":       "Bit31ErrFlag",
	"第7位必须是1":        "Bit7MustBe1",
	"纯净代码块":          "CleanCodeChunk",
	"纯数据":            "RawData",
	"纯数据载荷":          "PurePayload",
	"碎片":             "Frag",
	"碎片组":            "FragGroup",
	"目标":             "Target",
	"目标URL":          "TargetURL",
	"目标偏移":           "TargetOffset",
	"目标写入路径":         "TargetWritePath",
	"目标指针":           "TargetPtr",
	"目标日志文件":         "TargetLogFile",
	"目标服":            "TargetShard",
	"目标模组":           "TargetMod",
	"目标模组列表":         "TargetModList",
	"目标目录":           "TargetDir",
	"目标索引":           "TargetIdx",
	"目标路径":           "TargetPath",
	"目标路径集":          "TargetPaths",
	"目标集合":           "TargetSet",
	"织影者":            "Fuelweaver",
	"织影者倒计时":         "FuelweaverTimer",
	"蚁狮踩踏":           "AntlionStomp",
	"蚁狮踩踏分钟倒计时":      "AntlionStompMinTimer",
	"蛤蟆":             "Toadstool",
	"蛤蟆倒计时":          "ToadstoolTimer",
	"蜂后":             "BeeQueen",
	"蜂后倒计时":          "BeeQueenTimer",
	"现在":             "vNow",
	"生命周期":           "LifeCtx",
	"终止生命周期":         "KillSwitch",
	"绑定子进程生命周期":      "BindProcLifetime",
	"自裁标志":           "SuicideFlag",
	"缺失的配置":          "MissingConf",
	"缺换行符":           "MissingNL",
	"自动启动服务器":        "AutoStartServer",
	"自动安装":           "AutoInstall",
	"自定义等待时间":        "CustomWaitTime",
	"自身名称":           "SelfName",
	"磁盘彻底落盘缓冲毫秒数":    "DiskFlushDelayMs",
	"直连客户端":          "DirectClient",
	"监听控制台输入":        "ListenConsole",
	"看门狗":            "Watchdog",
	"竞速通道":           "RacingPipe",
	"端口":             "Port",
	"节点":             "Node",
	"节点_主世界":         "Node_Master",
	"节点_主世界_错误":      "Node_MasterErr",
	"节点_外部工具":        "Node_ExtTool",
	"节点_洞穴":          "Node_Caves",
	"节点_洞穴_错误":       "Node_CavesErr",
	"节点类型":           "NodeType",
	"节点锚点":           "NodeAnchor",
	"真实值":            "RealVal",
	"真实数据编号":         "RealDataIdx",
	"真实温度":           "RealTemp",
	"真实的文档路径":        "RealDocPath",
	"真实请求体":          "RealReqBody",
	"秒表":             "Stopwatch",
	"程序路径":           "BinPath",
	"系统时间":           "SysTime",
	"系统时间差":          "SysTimeDelta",
	"系统配置":           "SysConf",
	"索引":             "Idx",
	"纳秒差":            "NanoDelta",
	"绝对温度":           "AbsTemp",
	"绝对目标目录":         "AbsTargetDir",
	"绝对起始点":          "AbsStart",
	"行":              "Line",
	"行字节":            "LineBytes",
	"物理缓冲":           "PhysBuffer",
	"缓冲":             "Buffer",
	"缓冲指针":           "BufPtr",
	"解压流":            "UnzipStream",
	"解压熔断阈值":         "UnzipFuseLimit",
	"解压目标":           "UnzipTarget",
	"获取本地模组时间表":      "FetchLocalModEpochs",
	"获取远程模组更新时间":     "FetchRemoteModEpochs",
	"获取远程版本号":        "FetchRemoteVer",
	"获取默认存档根目录":      "FetchDefStorageRoot",
	"结果":             "Result",
	"结果集":            "ResultSet",
	"计算物理调度膨胀":       "CalcSchedBloat",
	"运行系统资源采集探针":     "BootSysProbe",
	"采集单进程数据":        "PollProcMetrics",
	"采集Win32数据":      "PollWin32Metrics",
	"进程差":            "ProcDelta",
	"进程状态":           "ProcState",
	"采样间隔":           "SampleInterval",
	"起始物理偏移":         "StartPhysOffset",
	"随父进程退出标志":       "PdeathSigFlag",
	"设置进程退出信号":       "SetProcExitSig",
	"进程结束信号":         "ProcExitSig",
	"进程名称":           "ProcName",
	"退出通道":           "QuitChan",
	"触发动作":           "FireAction",
	"语法树":            "AST",
	"解析API无符号整型":     "ParseApiUint",
	"解析API有符号整型":     "ParseApiInt",
	"解析Modoverrides": "ParseModOverrides",
	"解析Setup":        "ParseSetup",
	"解析二进制包":         "ParseRawPacket",
	"解析版本号":          "ParseVerNum",
	"设置位":            "SetBit",
	"连续内存块":          "ContigMemBlock",
	"限流读取器":          "ThrottleReader",
	"读取器":            "vReader",
	"读取总数":           "TotalRead",
	"读取行":            "ReadLines",
	"读取长度":           "ReadLen",
	"读前状态":           "PreReadStat",
	"读后状态":           "PostReadStat",
	"输出文件":           "OutFile",
	"输出阻塞锁":          "OutBlockLock",
	"跨域头":            "CorsHead",
	"路由":             "Route",
	"路由器":            "Router",
	"请求生命周期":         "ReqCtx",
	"请求载荷":           "ReqPayload",
	"载荷":             "Payload",
	"载荷长度":           "PayloadLen",
	"输出":             "vStdout",
	"记录的非零世代":        "LastValidEpoch",
	"远程时间":           "RemoteEpoch",
	"远程时间表":          "RemoteEpochMap",
	"远程版本":           "RemoteVer",
	"超时时间":           "vTimeout",
	"超时定时器":          "TimeoutTicker",
	"超时秒表":           "TimeoutStopwatch",

	"运行主世界":          "BootMaster",
	"运行洞穴":           "BootCaves",
	"跳过自检":           "SkipCheck",
	"跳过linux自检":      "SkipLinuxCheck",
	"跳过root自检":       "SkipRootCheck",
	"跳过root":         "SkipRoot",
	"通用启动参数":         "CommonBootArgs",
	"靶机":             "TargetHost",
	"配置文件目录":         "ConfDir",
	"配置":             "Config",
	"配置图":            "ConfigMap",
	"配置区1":           "Section1",
	"配置区2":           "Section2",
	"部分":             "Chunk",
	"默认主世界配置":        "DefMasterConf",
	"默认洞穴配置":         "DefCavesConf",
	"默认模板":           "DefTpl",
	"默认配置文件":         "DefConfFile",
	"默认cluster":      "DefCluster",
	"饥荒可执行文件名":       "DSTExecName",
	"邪天翁":            "Malbatross",
	"邪天翁倒计时":         "MalbatrossTimer",
	"龙蝇":             "Dragonfly",
	"龙蝇倒计时":          "DragonflyTimer",
	"震荡裂缝":           "CycleRift",
	"远端API":          "RemoteApi",
	"通过HTTP获取远程游戏版本": "FetchRemoteVerHTTP",
	"读取文件获取游戏版本":     "ReadLocalVer",
	"通道":             "Chan",
	"锁定状态":           "LockState",
	"错误通道":           "ErrPipe",
	"键":              "Key",
	"长度":             "vLen",
	"负数":             "IsNegative",
	"起始位置":           "StartPos",
	"递归填充":           "RecurseFill",
	"面板HTML":         "PanelHTML",
	"发现更新":           "UpdateAvailable",
	"饥荒世界生命周期":       "shardCtx",
	"终止饥荒世界生命周期":     "cancelShard",
	"运行版本监控":         "VersionProbe",
	"游标":             "vCursor",
	"底层监听":           "RawListen",
	"网络协议":           "vNetProtocol",
	"监听器":            "vListener",
	"远端世代传感器":        "RemoteEpochSensor",
	"杀掉进程":           "vKillProcess",
	"心跳信号":           "HeartbeatSignal",
	"怠速秒表":           "IdleStopwatch",
	"截断标志":           "TruncateFlag",
	"开始":             "vStart",
	"结束":             "vEnd",
	"当前周期":           "CurrentCycle",
	"洞穴命令前缀":         "cavesCommandPrefix",
	"洞穴命令前缀长度":       "cavesCommandPrefixLen",
	"终止函数":           "SeverancePayload",
	"旧指针":            "StaleArtifact",
	"主世界日志连接数":       "MasterLogConnCount",
	"主世界中央日志管道":      "MasterCentralLogChan",
	"主世界日志订阅":        "MasterLogSubChan",
	"主世界日志退订":        "MasterLogUnsubChan",
	"洞穴日志连接数":        "CavesLogConnCount",
	"洞穴中央日志管道":       "CavesCentralLogChan",
	"洞穴日志订阅":         "CavesLogSubChan",
	"洞穴日志退订":         "CavesLogUnsubChan",
	"广播日志块":          "BroadcastLogChunk",
	"块":              "vChunk",
	"引用数":            "RefCount",
	"日志广播池":          "LogBroadcastPool",
	"主世界日志广播中心":      "MasterLogBroadcastHub",
	"订阅者集合":          "vSubscribers",
	"洞穴日志广播中心":       "CavesLogBroadcastHub",
	"中央管道":           "vCentralChan",
	"连接数":            "vConnCount",
	"可能ID_num":       "ProbeIDNum",
	"id栈缓冲":          "IdStackBuf",
	"主世界mod配置路径":     "MasterModConfPath",
	"洞穴mod配置路径":      "CavesModConfPath",
	"cluster路径":      "ClusterPath",
	"主世界server配置路径":  "MasterServerConfPath",
	"洞穴server配置路径":   "CavesServerConfPath",
	"主世界world配置路径":   "MasterWorldConfPath",
	"洞穴world配置路径":    "CavesWorldConfPath",
	"mod更新配置文件路径集":   "ModUpdateConfPaths",
	"写入mod配置文件路径集":   "WriteModConfPaths",
	"游戏版本acf文件路径":    "GameVerAcfPath",
	"mod版本acf文件路径":   "ModVerAcfPath",
	"steamcmd程序路径":   "SteamCmdBinPath",
	"游戏程序路径":         "GameBinPath",
	"原子写文件流缓冲池":      "AtomicWriteStreamPool",
}

func main() {
	targetLang := flag.String("lang", "", "目标语言: -lang=en 或 -lang=zh")
	flag.Parse()

	if len(os.Args) > 1 && strings.HasPrefix(os.Args[1], "-") {
		lang := strings.TrimPrefix(os.Args[1], "-")
		if lang == "en" || lang == "zh" {
			*targetLang = lang
		}
	}

	if *targetLang != "en" && *targetLang != "zh" {
		os.Exit(1)
	}

	translateMap := make(map[string]string)
	if *targetLang == "en" {
		for zh, en := range dict {
			translateMap[zh] = en
		}
	} else {
		for zh, en := range dict {
			translateMap[en] = zh
		}
	}

	fset := token.NewFileSet()
	修改的文件数 := 0
	替换的变量数 := 0

	filepath.Walk(".", func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() || filepath.Ext(path) != ".go" {
			return nil
		}
		if filepath.Base(path) == "translator.go" {
			return nil
		}

		node, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if err != nil {
			fmt.Printf("[ERR] 无法解析 %s: %v\n", path, err)
			return nil
		}

		文件被修改 := false

		ast.Inspect(node, func(n ast.Node) bool {
			if ident, ok := n.(*ast.Ident); ok {
				if 目标词, 存在 := translateMap[ident.Name]; 存在 {
					ident.Name = 目标词
					文件被修改 = true
					替换的变量数++
				}
			}
			return true
		})

		if 文件被修改 {
			var buf bytes.Buffer
			if err := format.Node(&buf, fset, node); err != nil {
				fmt.Printf("[ERR] 格式化重写失败 %s: %v\n", path, err)
				return nil
			}

			if err := os.WriteFile(path, buf.Bytes(), 0644); err != nil {
				fmt.Printf("[ERR] 写入文件失败 %s: %v\n", path, err)
			} else {
				fmt.Printf("[OK] 已翻译: %s\n", path)
				修改的文件数++
			}
		}

		return nil
	})

	fmt.Printf("修改的文件总数: %d\n", 修改的文件数)
	fmt.Printf("发生替换的标识符总量: %d\n", 替换的变量数)
}
